#pragma config(Sensor, in1,    Potient,        sensorPotentiometer)
#pragma config(Sensor, in2,    Light,          sensorReflection)
#pragma config(Sensor, in3,    Gyro,           sensorGyro)
#pragma config(Sensor, in4,    RightLineFollow, sensorLineFollower)
#pragma config(Sensor, in5,    CenterLineFollow, sensorLineFollower)
#pragma config(Sensor, in6,    LeftLineFollow, sensorLineFollower)
#pragma config(Sensor, dgtl1,  Sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  LeftQuadEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  RightQuadEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  BackButton,     sensorTouch)
#pragma config(Sensor, dgtl8,  FrontButton,    sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port5,           crane,         tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
				this code makes it possible to use the controller to control what the robot does.
				We also created a "emergency stop" task that stops the DriveUsingController task.
*/

#include "../Head/constNumber.h"

task main()
{

	StartTask(battery);
	StartTask(EmergencyStop);

	while(true)
	{
		if(SensorValue(Light) < 200)
		{
			if(SensorValue(Sonar) > 30  || SensorValue(Sonar) == -1)
			{
				wait1Msec(200);
				motor[leftMotor] = 80;
				motor[rightMotor] = 80;
			}
			else
			{
				wait1Msec(200);
				motor[leftMotor] = -80;
				motor[rightMotor] = 80;
			}
		}
		else
		{
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}
	}


}
