#pragma config(Sensor, in1,    Potient,        sensorPotentiometer)
#pragma config(Sensor, in2,    Light,          sensorReflection)
#pragma config(Sensor, in3,    Gyro,           sensorGyro)
#pragma config(Sensor, in4,    CenterLineFollow, sensorLineFollower)
#pragma config(Sensor, in5,    RightLineFollow, sensorLineFollower)
#pragma config(Sensor, in6,    LeftLineFollow, sensorLineFollower)
#pragma config(Sensor, dgtl1,  Sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  LeftQuadEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  RightQuadEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  BackButton,     sensorTouch)
#pragma config(Sensor, dgtl8,  FrontButton,    sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port5,           crane,         tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	part one of 4, this code is responsible for the first part of what is supposed to happen.
	This is supposed to drive towards ball 1 which is all the way at the top
*/

#include "../Head/constNumber.h"

task main()
{
	//crane down and claw closed is the initial position of the robot's arm
	//make sure to get it back to that position before you pass it into the next task

	//you start always by calling this
	Begin();

	//you turn to whichever direction you want to go to first
	Turn(TURNDIST/2, false);
	//since there are some black lines while you're going through the middle
	//you want to ignore them and just drive forward for about 1.5m
	Drive(BASEDIST*2.5, true);
	//THEN you want to start the line sensor task
	startTask(DriveUsingLineSensor());
	//when he finds something that is infront of him he will stop driving and start picking up the item
	if(SensorValue(Sonar) < 15){
		StopTask(DriveUsingController());
		FullStopMotors();
		motor[crane] = -127;
		wait1Msec(10);
		motor[crane] = 0;
		motor[claw] = -127;
		wait1Msec(5);
		motor[claw] = 0;
		motor[crane] = 127;
		wait1Msec(5)
		motor[crane] = 0;
	}
	//when he's done picking up the item the crane should already be back in the air and the claw should be closed
	//then you want to burn 180 degrees and drive forward for half a meter
	Turn(TURNDIST, true);
	Drive(BASEDIST, true);

	//then you just want to repeat what you did above but in the opposite direction
	Turn(TURNDIST/2, true);
	Drive(BASEDIST*2.5, true);
	startTask(DriveUsingLineSensor());
	if(SensorValue(Sonar) < 15){
		StopTask(DriveUsingController());
		//set the crane back down as that is the initial position
		motor[crane] = -127;
		wait1Msec(5);
		motor[crane] = 0;
	}
}
